README.md

Updates reference to an old URL in the README (devicon.fr)

README: Update old URL

---

README.md

Hi! :slightly_smiling_face: 
Currently! In Section Contribute in README.md I think it would be better if we were to make text "Contributing.md" into a Link. So that anyone interested in contributing can look straight into it with a single click without going up and finding the file.

Minor enhancement section contribute.

---

devicon.json

Add missing icons to the devicon.json -> clojure, clojurescript and yunohost
Also resort 3 entries to their correct place

add clojure, clojurescript and yunohost to devicon.json

---

devicon.json

Added entry for redux to devicons.json

Add redux to devicons.json

---

assets/js/script.js

(ruby, rails, facebook, react, twitter, python,..)
fixes #326; fixes #162; fixes #63

fix svg rendering in preview window for showing the svg code 

---

.github/scripts/build_assets/drafts/peek_icons imgur.yml
.github/workflows/peek_icons.yml

Hi,
This PR has the same code as the PR in #452 .While I changed the `peek_icon.yml`, I still keep the old one in the `.github/build_assets/drafts` in case we ever get it to work.

Change the peek workflow to use upload artifacts

---

CONTRIBUTING.md
devicon.json

Somehow our `develop` branch was 3 commits behind the `master` branch. I merged them to fix this. This probably explains also the weird bot messages in #498 and #499.

merge master < develop

---

docs/index.html

This is an element that appears if you turned off javascript. You should probably fix the content but still

Noscript element on HTML

---

icons/matlab/matlab-line.svg

Updated the `matlab-line` icon. Address a part of the #788. 
EDIT: You can check out what the new peek-bot report on this icon [here](https://github.com/Thomas-Boi/devicon/pull/58)

new icon: matlab (line)

---

CONTRIBUTING.md
README.md

This PR contains minor updates to the `README` and `CONTRIBUTING`. It's mostly:
- Explaining new standards (e.g. no need to optimize files)
- Explaining new features (e.g. how to update an icon)
- Clarification on existing features (e.g. `develop` vs `master`)
- Minor fixes (e.g. missing entry in the table of contents)

Update the README and CONTRIBUTING.md

---

docs/assets/css/style.css
docs/index.html

- fixed `label for=""` id reference
- enhanced the popover (button:hover, close-button, box-shadow)

ui enhancements for color picker and report abuse (addition to #980)

---

.github/scripts/build_assets/selenium_runner/BuildSeleniumRunner.py

Fixed the issue caused by Selenium being unable to click on an element in the webpage.
Don't need to test the code. It's what we used before but later changed due to aesthetic reason. The broken code would only select the new icon to take a pic. This one would select everything so we'd have to look at every ourselves.
EDIT: There's only 1 line of code that was changed, which is line 95. IDK why the whole file was changed.

New Feature: Changed to select all rather before take a pic

---

.github/workflows/peek_icons.yml

Fix the issue seen in https://github.com/devicons/devicon/pull/1045#issuecomment-1066237780

Fix the peek bot cmd line args

---

.github/scripts/icomoon_build.py
.github/workflows/check_icon_pr.yml

Forgot to check for "update icon" PR name for icon PRs. This PR fixes it.
Please merge this PR in first. I want to test it against the confluence and bitbucket PRs.

Fix check icon not running for update icon pr

---

package-lock.json
package.json

A huge thanks to all our maintainers and contributors for making this release possible!
**1 New Feature**
- [Fix issue with npm publish script](https://github.com/devicons/devicon/pull/1084) by @amacado.

Build preparation for release v2.15.1

---

.github/scripts/build_assets/util.py
.github/scripts/check_icon_pr.py

Fix an issue seen in #1086 where the `check-bot` incorrectly mark the version name as wrong.

Fix checkbot's check version issue

---

devicon.json

During contributions, I noticed that the contents of the `devicon.json` file are not alphabetical. This is a PR to fix that. Hopefully, it'll be something that makes future contributions easier and more straightforward.
- Any existing PRs prior to this would need to be rebased after merge.
- I'm not sure of the impact on any Actions. Need confirmation.

Sort entries in devicon.json alphabetically

---

README.md

- Improve the Discord community text.

Improve the Discord community text

---

.vscode/extensions.json

This PR provides an essential recommendation to VS Code users who don't have installed `editorconfig` extension, as `.editorconfig` lints all files in this project.
VS Code `extensions.json` recommends this extension:
- **EditorConfig for VS Code**
- id: editorconfig.editorconfig
**This PR extends #1487**

add feature: vs code extension recommendations

---

devicon.json

Remove unicode character sequences from `devicon.json` which are likely culprits of builderror: https://github.com/devicons/devicon/actions/runs/3918634841
Remove unicode character sequences from `devicon.json` which are likely culprits of builderror: https://github.com/devicons/devicon/actions/runs/3918634841

Remove unicode chars from `devicon.json`

---

.github/workflows/build_icons.yml

- (Hopefully) fix workflow errors.

(Hopefully) fix workflow error

---

.github/workflows/in_develop_labeler_preflight.yml

- Update labeler preflight to Ubuntu Latest.

Update labeler preflight to Ubuntu Latest

---

package.json

- Run the server on the `docs` folder.

Run the server on the `docs` folder

---

devicon.json

Revert "bugfix/fix: references of `faunadb` and `ceylon`"

---

README.md

This PR closes NONE, just adds a new blank line in README.md before the code block to make the rendering correct.
BTW it's also possible to use more markdown syntax instead of  writing HTML manually.

docs(README): :bug: fix the code block rendering in the section of Install Selenium

---

README.md

Fix code block style

---

.github/scripts/requirements.txt

Requests < 2.32 are vulnerable. This should be updated immediately to avoid developers installing vulnerable versions of this package.
**This PR Closes #1771**
- https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q
- https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56

build(deps): bump requests from 2.31.0 to 2.32.3
