devicons/devicon

README.md, gulpfile.js, package.json
- upgrade gulp v3 to v4 and migrate gulp tasks; 
- documentation about the build process
=> Upgrade gulp and build documentation

index.html
As @samfuller01 pointed out in https://github.com/konpa/devicon/issues/163, [RawGit](https://rawgit.com/) has officially ended support in october 2019. [jsDelivr](https://www.jsdelivr.com/) looks like an easy to maintain replacement.
=> Migrate cdn from RawGit to jsDelivr

devicon-colors.css, devicon.json
The missing font property on redux leads to an js error in the gh-page which results into a incomplete listing of icons. Each icon below "redux" in `devicons.json` wasn't displayed on the gh-page.
=> fix devicon.json redux font property; remove grails original font

devicon.json
as reported in issue #373 github font is saved as original but the devicon.json is referencing the non-existing plain version
=> fix github font version and add alias (solves #373)

.github/workflows/build_icons.yml
Currently our font build process fail since it's not ready for `workflow_dispatch` trigger:
Since we are only triggering this action manually when a new release should be made we need to specify a fixed name for the resulting branch and can set the base to our master branch.
=> fix build process

.github/scripts/icomoon_peek.py, .github/workflows/build_icons.yml, .github/workflows/peek_icons.yml
Hello there,
This PR should allow us to upload images to the GitHub comments using GitHub Actions. You can see an example in the message below.
=> Add the public-upload-to-imgur action

docs/assets/js/script.js
Will close https://github.com/devicons/devicon/issues/444#issuecomment-753699913.
While fixing this bug in #444 I noticed some svg do not fulfill our viewbox requirement (128x128) and therefore the extracted code is wrong. I will create a extra issue for this bug.
=> fix displaying svg code in devicon.dev

devicon.json
There was an error with the sqlalchemy entry in the `devicon.json`. One of them involved putting the incorrect value into the `font` attribute. This was on me since I didn't explain it enough so I just fixed it.
=> Fixed an error with devicon.json

CONTRIBUTING.md
As the result of discussion #470 update guidelines with squash merging
=> Add guideline about squash merging

.github/scripts/build_assets/filehandler.py
add check for directory /icons when workflow is executed (fixes #505)
=> fix check svg icons workflow

.github/workflows/post_peek_screenshot.yml
This should fix the issue #510
=> Remove \n from script

.github/workflows/npm_publish.yml
I tried to work with https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idenvironment in the `npm_publish` workflow. This pull request will hopefully fix the workflow for the next release ;-) This time I will publish to npm by hand.
=> add environment for npm publish workflow

.github/workflows/post_check_svgs_comment.yml
I think I figure out the issue.
Here's what we want the bot to do:
Post a failure message if value is a text. This means the code is not `1` aka `SVG_STATUS_CODE.SVG_OK` or `0` aka `SVG_STATUS_CODE.NO_SVG`
Here's what the old check is:
```
(steps.err_message_reader.outputs.content != '0' || steps.err_message_reader.outputs.content != '1')
```
However, this would be interpreted differently by the script. If the `error_message` is `1`, it will trip the first check. If the `error_message` is `0`, it will trip the second cause OR operators check terms until one is true. 
Pretty much, this is the wrong check. Using OR in human language is different than OR in computer and I forgot to "translate" it.
Here's the new check: 
```
(steps.err_message_reader.outputs.content != '0' && …
```
=> Fix the issue with "Post Check SVG" posting the wrong message

CONTRIBUTING.md, README.md
Since this project is evolving and [new people want to join the team](https://github.com/devicons/devicon/pull/507#issuecomment-784438799) I was thinking about introducing github teams for managing permissions and responsibilities. I'm not into hierarchical structures, but for security reasons (this little project is already used by a significant amount of people) I think we should introduce some permissions and trust system to ensure integrity. 
So this pull request is open for discussion and everyone is allowed and asked for his/her opinion.
=> introducing teams and guidelines for supporters

.github/workflows/npm_publish.yml, .github/workflows/post_check_svgs_comment.yml, CONTRIBUTING.md, README.md, package.json
**Pending**
**Fixes**
- Workflow "npm publish": Add environment for npm publish workflow (#513)
- Workflow "Check SVGs": Change the boolean in post_check_svgs_comment (#515)
**Documentation**
- Introducing teams and guidelines for supporters (#516)
Thanks to @Thomas-Boi for contributing to this release.
=> Release v2.10.1

.github/workflows/peek_icons.yml, .github/workflows/post_check_svgs_comment.yml, .github/workflows/post_peek_screenshot.yml
This PR should fix the issue mentioned in #514 .
What's new:
The "post_peek_screenshot" will now check for three different states of the trigger "peek_icons" action: "skipped", "success", and "failure. These values have to be found by console logging the `github.event` object. The docs don't mention this for some reason.
Also, GitHub Actions will construct env variables before an if check by default:
Before, there was an env variable that relies on a skipped step => script was failing since it couldn't construct this variable.
That's pretty much it. I've tested it using my forked branch. The behaviours are:
- If "peek_icons" was skipped (label incorrect), the "post_peek_action" would also skip
- If "peek_icons" was successful, the "post_peek_action" would post successful message
- If …
=> Fix issue with "post_peek_screenshot" action failing when it's not supposed to

.github/workflows/stale.yml, README.md
- Configure/setup [Stale](https://github.com/marketplace/actions/close-stale-issues) workflow.
=> feat: Setup Stale workflow

package-lock.json
- Fix alerts reported by [Dependabot](https://github.com/devicons/devicon/security/dependabot/package-lock.json/yargs-parser/open).
- The `integrity` keys may need to be modified.
=> fix: Alerts reported by Dependabot

.github/scripts/icomoon_peek.py
- Fix link reference in `.github/scripts/icomoon_peek.py` when the build fails.
=> Fix link reference in `.github/scripts/icomoon_peek.py`

.github/PULL_REQUEST_TEMPLATE/new_icon.md
This occurs to me while I was working on the stale PRs. This is to ensure the SVGs are up to date when it is submitted into the repo.
=> Add extra requirement in new icon pr template

devicon.json, icons/rstudio/rstudio-original.svg, icons/rstudio/rstudio-plain.svg
Taken from #116. Work was done by @Pmz64. I modified the plain version to get the original version.
=> new icon: rstudio (original, plain)

.github/workflows/build_icons.yml, .github/workflows/post_peek_screenshot.yml
This will hopefully fix https://github.com/devicons/devicon/pull/646#issuecomment-849959829
=> update public-upload-to-imgur action v2.2.2

.github/scripts/icomoon_build.py
Before, the bot will parse the PR titles and find the corresponding font object in the `devicon.json` without any checks. Thus, this causes an error when the `tailwindcss` was added in two separated PR.
Fix:
The bot will now ensure the `devicon.json` object is unique within the build list.
=> Fix duplicated past icons in build process

.github/scripts/build_assets/api_handler.py
GitHub API has some none-standard attributes. Originally, I use this, which has the proper name:
However, sometimes GitHub will reveal the actual user's name, which makes it impossible to reference using the `@` character (see #676)
And weirder still, there is another field that contains the proper GitHub name that can be tagged using the `@`. However, not all PRs have it:
Proper:
Bug:
**FIX**
Use the proper `[author][login]` name. If there's an error, use the non-consistent `[commit][author][name]`
=> Fixed issue with wrong name referencing from github api

.github/scripts/build_assets/arg_getters.py, .github/scripts/icomoon_peek.py
This fixes the issue seen in #691 with the peek bot.
Issue:
- The script failed because the script requires a `token` command line arguments. However, peek bot does no need them.
Reason:
- The build bot and peek bot share most of the same command line arguments. One of them, the `token`, was recently added and was meant for build bot only. However, I forgot to enforce that by accident.
- The fix uses an existing check to ensure only the build bot requires the token
=> Only build script will need token API

CONTRIBUTING.md
The file name example is wrong for the plain version, as shown below:
This PR just fixes that.
=> Fix plain icon example on CONTRIBUTING

.github/workflows/npm_publish.yml
The workflow for publish to npm doesn't have a 
```yml 
name: 
```
so I added it
=> Publish to npm name

gulpfile.js
=> Gulpfile Edits

devicon.json
- Remove aliases in the OpenGL icon as they're not needed.
=> Remove aliases in the OpenGL icon as they're not needed

gulpfile.js, package-lock.json, package.json
**Fixes**
- Addressed the security issues that I can. Here's the latest audit
- The issues that are left can't be fixed by me. The modules listed (`yargs` and `glob-parent`) are used by `gulp`'s latest version and there's nothing I can do to upgrade them. Luckily, since the scripts don't accept user inputs, we should never run into any issues as listed by `npm audit`
- This also added `gulp-footer`, which will be used by my upcoming `seleniumUpgrade`. There's no usage of it yet, I just added the package to see if I need to address any security
**Test**
Here's the latest script testing the `sass` modules.
**Notes**
This took a while because it requires the `socketio` fix and the `open-gl` fix.
Also, when you accept this PR, rename the commit to "Close #763: Update NPM packages". I want to …
=> Fix issues with npm security

icons/clojurescript/clojurescript-plain.svg
Update the `clojurescript-plain` icon as seen in #788. You can also view the new peek-bot's report on this icon [here](https://github.com/Thomas-Boi/devicon/pull/59).
=> new icon: clojurescript (plain)

icons/markdown/markdown-original.svg
Removed strokes from `markdown-original`. This should be the last SVG that has strokes in them.
EDIT: You can view the new peek-bot result [here](https://github.com/Thomas-Boi/devicon/pull/66)
=> new icon: markdown (original)

.github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/icon_request.yml
- Fixed the issue templates having some syntax errors.
- Sorry for removing the PR template, but this is just a simple bug fix, so I don't think it needed the template. 😅
- Closes #814.
=> Fix syntax with the issue templates

CONTRIBUTING.md
Added a header for the bug section in `CONTRIBUTING.md` so we can refer people to that section.
=> New Feature: Update the docs for CONTRIBUTING.md

docs/assets/js/script.js, docs/index.html
Adds a section to display the `<img>` of the selected SVG to the website. 
This offers users an option to link external SVGs rather than using inline/pure SVGs. This will change dynamically depending on the currently selected SVGs.
I've tested the feature and here's what it looks like:
The feature above was inspired by [this site](https://renevds.github.io/language-icon-widget-pages/#/) which was submitted by @renevds on Discord.
Also redo the icon section and add a hint on how to increase the icon's size:
Later on, I'll work on a copy button to make things easier for the user. That'll be in a separate PR.
=> New Feature: webpage now displays <img> of SVG

docs/index.html
=> feat: Improve SEO

CONTRIBUTING.md
Added a new section to `CONTRIBUTING.md` like we discussed in the Discord channel.
@Panquesito7 Take a look if you want :)
=> Added resources section to `CONTRIBUTING.md`

.github/scripts/build_assets/filehandler.py, .github/scripts/check_icon_pr.py
- [X ] PR does not match another non-stale PR currently opened
- [ X] PR name matches the format *New Feature: a brief description of feature*
One of the function was named incorrectly.
=> new feature: fix invalid function name

.github/scripts/build_assets/api_handler.py, .github/scripts/build_assets/filehandler.py, .github/scripts/build_assets/selenium_runner/BuildSeleniumRunner.py, .github/scripts/build_assets/selenium_runner/PeekSeleniumRunner.py, .github/scripts/build_assets/selenium_runner/SeleniumRunner.py, .github/scripts/build_assets/util.py, .github/scripts/icomoon_build.py, .github/workflows/build_icons.yml, gulpfile.js
- [ X] PR does not match another non-stale PR currently opened
- [ X] PR name matches the format *New Feature: a brief description of feature*
The build-bot fixes problems with:
- The zip file generated by Icomoon couldn't be unzipped => add a function to fix the zipfile
- Some Selenium action were timed improperly => add waits and retries to address that
- Logging for build bot is not in order due to GitHub => logging will now be done via a log_file that'll be uploaded as an artifact.
I tested the fix with my forked branch. You can check out the [actions results](https://github.com/Thomas-Boi/devicon/actions) and the [PR](https://github.com/Thomas-Boi/devicon/pull/103) to double check. However, I wasn't able to test the `in-develop` closer here. Hopefully, this is still functional.
=> Add fix for bad zip file and logging for build

devicon.json, icons/ballerina/ballerina-line-wordmark.svg, icons/ballerina/ballerina-line.svg, icons/ballerina/ballerina-original-wordmark.svg, icons/ballerina/ballerina-original.svg, icons/ballerina/ballerina-plain-wordmark.svg, icons/ballerina/ballerina-plain.svg
* [ballerina.io](https://ballerina.io/)
* [ballerina playground](https://play.ballerina.io/)
=> new icon: ballerina (original, plain, line, original-wordmark, plain-wordmark, line-wordmark)

devicon.json
- Add `original-wordmark` aliases for Liquibase.
- Thanks to @kilian-paquier for spotting the bug!
=> fix: add `original-wordmark` aliases for Liquibase

.github/PULL_REQUEST_TEMPLATE/new_icon.md, .github/workflows/post_check_icon_pr_comment.yml, .github/workflows/post_peek_screenshot.yml
fix #1328
Didn't update link in index.html since it doesn't point to a specific place in CONTRIBUTING.md. For a general overview, the CONTRIBUTING.md file is still the best option imo.
=> updated links to contributing guidelines

.editorconfig, devicon.json
This PR is based on this discussion https://github.com/devicons/devicon/issues/1337 , the idea was, as a first step, to add **EditorConfig** to the project, and I also fix bad formatting on the JSON file.
**EditorConfig** helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a file format for defining coding styles and a collection of text editor plugins that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.
When you work on a file, and for example press the <kbd>tab</kbd> key , you will automatically insert the correct indent type and length, for **Devicon** it's `space of …
=> Add editorconfig file and cleanup `devicon.json` bad formatting

CONTRIBUTING.md
- Improve contributing deprecation notice.
=> docs: improve contributing deprecation notice

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/icon_request.yml, .github/ISSUE_TEMPLATE/other.yml, .github/PULL_REQUEST_TEMPLATE/new_feature.md, .github/drafts/stale.yml, .github/pull_request_template.md
- Minor template/stale message improvements.
=> Minor template/stale message improvements

.github/ISSUE_TEMPLATE/feature_request.yml
- Improve the feature request template.
=> Improve the feature request template

.github/PULL_REQUEST_TEMPLATE/new_icon.md, .github/workflows/post_peek_screenshot.yml
It is however related to #1327
=> Add alphabetical ordering of `devicon.json` to PR checklist

.github/pull_request_template.md
add ![][~feature:icon] and ![][~enhancement] labels to pull_request_template.md, so that the labels are added automatically when users copy the link
**This PR closes #1399**
I think this needs to be merged to master before it takes effect
[~feature:icon]: https://img.shields.io/badge/-feature:icon-6cc43c.svg
[~enhancement]: https://img.shields.io/badge/-enhancement-84b6eb.svg
=> add feature:icon and enhancement labels automatically

devicon.json
Maybe it's duplicated. `tauri`. So, I try to remove one 🙏!
https://github.com/devicons/devicon/blob/4f550268010eaf18b7713de5ee1fd94eb5959d16/devicon.json#L8558-L8606
=> fix: remove duplicate `tauri` icon entry

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/icon_request.yml, .github/ISSUE_TEMPLATE/other.yml
Update issue templates, see #1467 for some reasons why this is useful
**This PR closes #1467**
=> Improve the issue templates

.github/workflows/build_icons.yml, package.json
- Update and use Geckodriver for Linux64.
- We might want to make sure the newest Geckodriver version works. If it doesn't, we can always revert back to the other version.
- The Windows build is kept in the `build_assets` folder in case it's needed again. If wanted, we can delete it.
=> Update and use Geckodriver for Linux64

.github/workflows/build_icons.yml
- Fix token error.
- This should fix the error with the Build Icons workflow. The way the token's being accessed in Windows and Ubuntu changes, which caused the error. Should be reviewed/merged ASAP.
=> Fix token error

README.md, docs/assets/css/style.css, docs/assets/js/script.js, docs/index.html
**This PR closes #1218**
Executed locally with python http.server. Feel free to write a review.
=> new feature: icons number

.github/workflows/codeql-analysis.yml
- x] PR does not match another non-stale PR currently opened
It appears that by default codeql does not look into the `.github` directory, and as a result, all executions fail as python is listed, but no `.py` scripts exist outside that hidden directory.
To address this, this PR splits the codeql initialization and analysis into three parallel jobs, one for javascript, one for python that runs in `.github/`, one optional python for the rest in case we later add python scripts outside the `.github/` directory.
Here are some screenshots from the testing:
=> Update codeql-analysis to run on .github

.github/workflows/build_icons.yml
Skips `imgur_step` and removes the lines related to this step on `release_message_step`. It also uses the last version of Windows, GitHub Checkout, Setup Python and Python on 3.10 version.
=> Fix build icons workflow

devicon.json
This pull request fix errors of reference in `devicon.json` file for each of icons listed below:
- capacitor
- elasticsearch
- heroku
- hibernate
- jaegertracing
- karatelabs
- kibana
- ktor
- livewire
- llvm
- logstash
- nginx
- nhibernate
- okta
- opentelemetry
- postman
- quarkus
- quasar
- sqldeveloper
- unidifimodelinglanguage
Some icons were not displayed purely because of reference errors in `devicon.json` file.
=> bugfix/fix: `devicon.json` reference errors

devicon.json
**This PR partially closes #1998**
=> bugfix/fix: references of `faunadb` and `ceylon`

.github/workflows/build_icons.yml, .github/workflows/check_icon_pr.yml, .github/workflows/codeql-analysis.yml, .github/workflows/in_develop_labeler.yml, .github/workflows/in_develop_labeler_preflight.yml, .github/workflows/npm_publish.yml, .github/workflows/peek_icons.yml, .github/workflows/post_check_icon_pr_comment.yml, .github/workflows/post_peek_screenshot.yml
Some actions are deprecated and will automatically fail the job if those versions are specified.
See: https://github.com/ReenigneArcher/devicon/actions/runs/12240230225/job/34142538368
- Trailing white space was removed.
- Indentation of `types:` was corrected in the `peek_icons.yml` workflow.
=> ci(workflows): update deprecated actions

README.md, package-lock.json, package.json
This PR makes it so `npm run build-icons` works on all standard OSes.
A new dev dependency was added to simplify this: https://www.npmjs.com/package/run-script-os
Edit: This is draft as I discovered it is not using the activated python venv. Will update once resolved.
=> build(npm): automatically run build-icons for correct os
